### PR TITLE
Add terms

### PR DESCRIPTION
**Pull request by egbendito**
This adds *eia-specific* terms to the repository to facilitate the naming conventions of the datasets.

### CODE REVIEW

**Comment by egbendito** [comment]
@cedricngakou please, review this PR carefully, as it introduces some major changes on how we operate in the repo. So far it does not (*SHOULD NOT*) break anything, but it works as a proposal of how we can work in this project-specific carob.

In principle, the files in `terms/` need to be copied to the relevant folder (), typically the `carobioner` installation. The target can be looked-up by:

```R
list.files(system.file("terms", package="carobiner")
```

This can be the basis of how we also tweak the more general terms for project-specific `carob` implementations.

**Comment by egbendito** [comment]
Also tagging @rhijmans

**Comment by rhijmans** [comment]
I would want to avoid copying files to the carobiner folder.  Instead, I would like to ask carobiner to look in the terms folder of your repo (or another such folder where you store your additional vocabulary) and let carobiner do the appending (I can add that functionality). I could do this with "settings" that would also allow (with some more work) to use a different controlled vocabulary than terminag. 

I see two new "values" files and that is straightforward, but they won't be used unless they are listed as "vocabulary" for variables in "variables_metadata.csv". You could add a "variables_metadata.csv" file but you should not copy existing variables, only your project-specific variables so that they can be appended to the terminag variables.

**Comment by egbendito** [comment]
What I have tested:

```R
write("eia,crop; soil,eia data",
      file = list.files(system.file("terms", package="carobiner"), pattern = "groups", full.names = TRUE),
      append = TRUE)

# Add use case list to terms
# # Values
# # # Use Cases
j <- httr::GET("https://my.eia.cgiar.org/api/v1/usecases/")
json <- jsonlite::fromJSON(rawToChar(j$content))[,c(3,4,2)]
colnames(json) <- c("name", "long_name", "myeia_code")
write.table(json, paste0(list.files(system.file("terms", package="carobiner"),
                                    pattern = "values",
                                    full.names = TRUE),
                         "/values_eia_usecases.csv"),
            sep = ",", row.names = FALSE)
# # # Activities
act <- data.frame("name" = c("addon", "validation", "piloting", "scaling", "experiment", "survey", "other"),
                  "long_name" = c("Add-On", "Validation", "Piloting", "Scaling", "Experiment", "Survey", "Other"),
                  "description" = c("EiA step-?", "EiA step-5", "EiA step-6", "EiA step-7", "Some form of experimental data the use case has collected to calibrate or test their MVP. These include Nutrient Ommission Trials (NOTs), planting date experiments, or other form of researcher managed experiments.", "Previous surveys conducted by the use case. This can be linked to baselines, etc.", "Any other type of datasety the use case has acquired such as compiled data provided by partners, literature review, or other."))
write.table(act, paste0(list.files(system.file("terms", package="carobiner"),
                                    pattern = "values",
                                    full.names = TRUE),
                         "/values_eia_activities.csv"),
            sep = ",", row.names = FALSE)

# # Variables
# # # Use Cases
write("use_case,character,,yes,eia_usecases,no,,,yes,,,",
      file = list.files(system.file("terms", package="carobiner"), pattern = "variables_metadata", recursive = TRUE, full.names = TRUE),
      append = TRUE)
# # # Activities
write("activity,character,,yes,eia_activities,no,,,yes,,,",
      file = list.files(system.file("terms", package="carobiner"), pattern = "variables_metadata", recursive = TRUE, full.names = TRUE),
      append = TRUE)
```
This writes only the `values_eia_usecases.csv` and `values_eia_activities.csv` and appends the relevant info to `groups.csv` and `variables_metadata.csv`.

If we can put our modified terms into the `terms` folder in the `eia-carob` repository and have `carobiner`pick it up from there and append where relevant, it would be best. I guess the `eia-carob` specific terms would still need to maintai the name convention of the `variables_<attribute>.csv` for any existing set of terms/values.

**Comment by rhijmans** [comment]
You can create a solution like that, but you would need to run this each time that terminag updates

**Comment by egbendito** [comment]
And putting the new `variables` and `values` in respective csv files in the `eia-carob/terms` folder? 

Then `carobiner::update_terms()` can look into what is there (local repo) and add it to the local carobiner package. That is done everytime the terms are updated, so that the newest standards take precedence, and _then_ look into the project-specific `terms`

**Review by cedricngakou — APPROVED** [review]

**Comment by egbendito** [comment]
We went head and merged this changes into the repository, as a proposal. We need to figure how to align the processes so that `carobiner` can aid to integrate new "custom" terms.

**Pull request merged**
